GET http://localhost:3000/wines

###

GET http://localhost:3000/wines/6079fe46fed94b637f1e896f

###

POST http://localhost:3000/wines
Content-Type: application/json

{
    "name": "Test Wine",
    "country": "Test Country",
    "region": "Test Region",
    "price": 1111,
    "year": 2222
}

###

DELETE http://localhost:3000/wines/6079fe46fed94b637f1e896f